Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -60,15 +60,26 @@ jobs:
           npm ci
         fi
         
-    - name: Build and Test
+    - name: Build
       run: |
         if [ -f package-lock.json ]; then
           npm run build --if-present
-          npm test
         elif [ -f pnpm-lock.yaml ]; then
           pnpm run build --if-present
-          pnpm test
         else
-          echo "Lock file not found. Cannot run build or test scripts."
+          echo "Lock file not found. Cannot run build scripts."
           exit 1
+        fi
+
+    - name: Test
+      run: |
+        if [ -f "package.json" ] && [ "$(node -p "require('./package.json').scripts && require('./package.json').scripts.test")" ]; then
+          if [ -f "package-lock.json" ]; then
+            npm test
+          elif [ -f "pnpm-lock.yaml" ]; then
+            pnpm test
+          else
+            echo "Lock file not found. Cannot run test scripts."
+            exit 1
+          fi
         fi
